### ISSUE TITLE
how to update options during interaction, how to stop interaction?

### ISSUE THREAD

**Issue by rozek** [marcospont/agnostic-draggable#1]
Hello,

at first, thanks a lot for this wonderful contribution: for quite a while, I thought about implementing s.th. similar myself - but always withdrew that idea because of the foreseeable effort.

But now, everything I had to do was to write a trivial [wrapper](https://github.com/rozek/svelte-agnostic-draggable) around your module in order to use it with [Svelte](https://svelte.dev/repl/cc36f2c307d54b0081fd6a16c18d1b5f).

However, that work raised a few questions, two of them are:

* is it possible to update the initially given options while an interaction is ongoing? (e.g., the "containment" of a "draggable")
* is it possible to stop (i.e. abort) an ongoing interaction? (e.g. an ongoing drag-and-drop operation by means of the ESC key)

Thanks in advance for your effort!

Kind regards,

Andreas Rozek

**Comment by marcospont** [comment]
Hello @rozek 

Sorry for the delayed answer. Very glad to know that you liked the work done here.

About updating options during interaction, my initial assumption is that is possible. Need to perform tests though.

About aborting an ongoing interaction, this is one of the many behaviours that jQuery UI already had and should be available in agnostic-draggable as well. Also needs test to confirm, but I'm almost sure stopping/cancelling on the fly is perfectly possible.
