### ISSUE TITLE
Update disabled

### ISSUE THREAD

**Issue by awpyix** [marcospont/agnostic-draggable#12]
Is it possible to update disabled option on draggable component ? It doesnt seem to update if i create it like this (this.lock = prop): 
`    new Draggable(this.$refs.Item, {
      helper: "clone",
      containment: "body",
      zIndex: 5,
      disabled: this.lock
    });`

**Comment by awpyix** [comment]
oh i guess assigning it to a variable and then updating it with x.options.disabled works, not auto tho :(

**Comment by marcospont** [comment]
@awpyix I will take a look at the first scenario 'cause it should work.

Thanks

**Comment by marcospont** [comment]
@awpyix the commit c20a4715a97f89376f8f02e7bed55afebc13db64 included a 'setOption' for all widgets that allows to dynamic change all options that can be dynamically changed.

The documentation was also updated to indicate which options can be changed dynamically.
