### ISSUE TITLE
In jQuery draggable they have an option, "cursorAt". Is there an equivalent of this in agnostic-draggable?

### ISSUE THREAD

**Issue by adrianpdaluz** [marcospont/agnostic-draggable#13]

**Comment by adrianpdaluz** [comment]
My workaround to this is I extended the Draggable class and overridden the calculatePosition function to update the offsets using the helper size.

calculatePosition(event, constraint = true) {
    super.calculatePosition(event, constraint);
    const cursorAt = this.options.cursorAt;
    if (cursorAt) {
      this.adjustOffsetFromHelper(cursorAt);
    }
  }

  adjustOffsetFromHelper(obj) {
    if (typeof obj === 'string') {
      obj = obj.split(' ');
    }
    if (Array.isArray(obj)) {
      obj = { left: +obj[0], top: +obj[1] || 0 };
    }
    if ('left' in obj) {
      this.offset.click.left = obj.left + this.margins.left;
    }
    if ('right' in obj) {
      this.offset.click.left = this.helperSize.width - obj.right + this.margins.left;
    }
    if ('top' in obj) {
      this.offset.click.top = obj.top + this.margins.top;
    }
    if ('bottom' in obj) {
      this.offset.click.top = this.helperSize.height - obj.bottom + this.margins.top;
    }
  }

**Comment by marcospont** [comment]
Hello @adrianpdaluz 

The 'cursorAt' option from the jQuery widgets was not ported to this library. Seemed at the time that it was one of the least important options to be ported.

If you like to address this gap, feel free to submit a PR.

Thanks :)
