### ISSUE TITLE
Remove the event from an `Element`

### ISSUE THREAD

**Issue by AlanBlanchet** [marcospont/agnostic-draggable#14]
Hello community,

I haven't found in the docs how to remove the event from the `Element`.
Is there a way to do so ?

Thanks

**Comment by marcospont** [comment]
Hello @AlanBlanchet 

Can u elaborate your question better?

**Comment by AlanBlanchet** [comment]
Hello @marcospont 

Sure I'll elaborate the question.

In the docs it says how to create a draggable event with the object : 
```typescript
new Draggable(document.body, {
	axis: 'x'
});
```

But if I want to remove the event, how do I do it ?

With vanilla js you would do : 
```javascript
const f = (e) => console.log(e)
document.body.addEventListenener("drag", f)
// Do stuff
// .....
// .....
document.body.removeEventListener("drag", f)
```

**Comment by marcospont** [comment]
@AlanBlanchet 

The element passed to the Draggable constructor should be the actual element to be dragged.
I don't think it makes sense to drag the document's body :)

About attaching and detaching of events, the destroy() method of the Draggable class is supposed to remove all event listeners. By the way, all event listeners used to allow elements to be draggable are attached to the document, not to the draggable elements.
