### ISSUE TITLE
Guarantee revert 'valid' or 'invalid'

### ISSUE THREAD

**Issue by emersonhinterholz** [marcospont/agnostic-draggable#18]
https://github.com/marcospont/agnostic-draggable/blob/b1b144a67116195b3e4744718e7ef638ce48f8c6/src/draggable/draggable.js#L457

Here, configuring the revert as any string, the code will consider as a true boolean. Probably a revert === true would fix.

**Comment by marcospont** [comment]
This issue was fixed by [https://github.com/marcospont/agnostic-draggable/commit/b0cd9bae5cb61cfc4ffa48caa0902b6cbed27a47](https://github.com/marcospont/agnostic-draggable/commit/b0cd9bae5cb61cfc4ffa48caa0902b6cbed27a47).
