### ISSUE TITLE
Documentation for data returned by events

### ISSUE THREAD

**Issue by brandonmcconnell** [marcospont/agnostic-draggable#3]
Could you build upon the documentation to clarify some of the data that is returned?

Immediately, I am looking to use `peerSortable` but I do not know the nature of its data and if it is always present and/or reliable, and if it is always the previously connected sortable or something else.

**Comment by marcospont** [comment]
The `README.md` file was updated by adding documentation about all arguments passed to events in the library.

After committing the change, I have noticed some bad formatting on the list of arguments of each event. Will fix this in the next opportunity, hopefully it can help you understand those events.

https://github.com/marcospont/agnostic-draggable/blob/main/README.md

Thanks,
Marcos
