### ISSUE TITLE
Position/index of sorted element(s) before/after moved

### ISSUE THREAD

**Issue by brandonmcconnell** [marcospont/agnostic-draggable#4]
It would be helpful to see both the previously selected sortable and the moved element's previous position/index in that list as well as the new sortable it is a part of and its new position/index.

I see a position property, but it returns all null values. — _see attached_
![E8c09D3X0AccQI_](https://user-images.githubusercontent.com/5913254/128923398-18493775-ba18-4d51-8828-d069a94a43ea.png)

**Comment by marcospont** [comment]
The `sortable:update` event was changed to include more arguments, including the previous and the new indexes of any element being sorted within a single sortable or between two sortable instances.

The following commit addresses your suggestion:
https://github.com/marcospont/agnostic-draggable/commit/08902cd0451b6e3066a26189b8627b49f1b37e41

Thanks,
Marcos
