### ISSUE TITLE
Add event for re-ordering element within sortable

### ISSUE THREAD

**Issue by brandonmcconnell** [marcospont/agnostic-draggable#5]
I have been exploring all the events currently available, and it appears the most relevant event to an element being reordered in the same sortable is `sortable:update`, however that returns all the data for the sortable the element is connected to, not the element itself.

More appropriately, the `sortable:remove` and `sortable:receive` events return data about the elements themselves when they are added/removed from a sortable, but there appears to be no equivalent event for when an element is reordered within the sortable it is already a part of. I understand that technically, many elements are reordered simultaneously when one element is reordered, however, if there were some separate `sortable:reorder` event fired for the element actually dragged and dropped including its previous and new position/index within the list, the rest could be easily inferred.

In the case of linked arrays, this would be helpful so I could splice the element from its previous position/index to its new one.

**Comment by marcospont** [comment]
The `sortable:receive`, `sortable:remove` and `sortable:update` events were updated with new arguments.

More specifically, you will be able to get the `previousIndex` and the `newIndex` of any element being sorted inside a sortable instance or moved from one sortable to another.

The following commit addresses your suggestion:
https://github.com/marcospont/agnostic-draggable/commit/08902cd0451b6e3066a26189b8627b49f1b37e41

Thanks,
Marcos
